final Map<String, List<String>> categoryToTypes = {
  'Móveis e utensílios': [
    'Armário',
    'Baias',
    'Cadeira',
    'Balcão',
    'Hack',
    'Mesa',
    'Microondas',
    'Móveis Planejados',
    'Móvel Bar',
    'Sofás',
    'Ar Condicionado',
    'Base de Metal',
    'Tampo de granito',
    'Criado mudo',
    'Geladeira',
    'Bebedouro',
    'Fogão',
    'Cervejeira',
    'Freezer',
    'Máquina de café expresso'
  ],
  'Equipamentos de informática': [
    'Monitor',
    'Cpu',
    'Celular',
    'Tablet',
    'Nobreak',
    'Estabilizador',
    'Impressora',
    'Notebook',
    'Macbook',
    'Televisão',
    'Retoprojetor',
    'NETTOP',
    'Microcomputador',
    'Mini projetor',
    'Controlador de Acesso Biométrico',
    'Leitor Laser',
    'Wireless',
    'HD Externo',
    'Interfone',
    'Broadcast',
    'Sensor Kinect',
    'Chipeira',
    'Switch',
    'DVR',
    'Chaveador',
    'Patch Panel',
    'Fragmentadora',
    'Leitor biométrico',
    'Servidor',
    'Router Board',
    'Aparelho de registro de ponto'
  ],
  'Bens de pequeno valor': [
    'Mouse',
    'Teclado',
    'Headset',
    'Fones de ouvido',
    'Cabos',
    'Fonte de alimentação',
    'Fonte POE 24V 1A',
    'Suporte pedestal',
    'Claviculário',
    'Bandeja porta cápsula de café',
    'Interfone'
  ],
  'Veículos': ['Onix', 'Tracker', 'Versa'],
};
